version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/qjoly/une-pause-cafe:latest
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html