name: Publish Program

on:
  push:

jobs:
  publish:
    name: Publish Program
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Construire et pousser l'image Docker
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u qjoly --password-stdin
          docker build -t ghcr.io/qjoly/une-pause-cafe .
          docker push ghcr.io/qjoly/une-pause-cafe

      - name: Curl vers Blinky
        run: curl https://app.getblinky.io/api/v1/ingest/webhook/9da47c43-a027-47cb-beee-eb81bb90ecfa
